- defaults:
    link:
      relink: true
      force: true

- clean:
    ~/.config:
      recursive: true

- create:
    - ~/.config
    - ~/.config/direnv
    - ~/.config/ssh
    - ~/.config/zsh
    - ~/.config/zsh/functions

- link:
    # zsh
    ~/.zshenv: ~/.dotfiles/etc/zsh/.zshenv
    ~/.config/zsh/.zshrc: ~/.dotfiles/etc/zsh/.zshrc
    ~/.config/zsh/.zsh_plugins.txt: ~/.dotfiles/etc/zsh/.zsh_plugins.txt
    ~/.config/zsh/.aliases: ~/.dotfiles/etc/zsh/.aliases
    ~/.config/zsh/.zprofile: ~/.dotfiles/etc/zsh/.zprofile
    ~/.config/zsh/.utils: ~/.dotfiles/etc/zsh/.utils
    ~/.config/zsh/.zstyles: ~/.dotfiles/etc/zsh/.zstyles
    ~/.config/zsh/functions:
      glob: true
      path: ~/.dotfiles/etc/zsh/functions/*
      relink: true
    ~/.config/zsh/.p10k.zsh: ~/.dotfiles/etc/zsh/.p10k.zsh
    ~/.config/zsh/.fzf.zsh: ~/.dotfiles/etc/zsh/.fzf.zsh

    # editorconfig
    ~/.editorconfig: ~/.dotfiles/etc/.editorconfig

    # git
    ~/.gitconfig: ~/.dotfiles/etc/git/.gitconfig
    ~/.gitignore_global: ~/.dotfiles/etc/git/.gitignore_global
    ~/.gitattributes: ~/.dotfiles/etc/git/.gitattributes

    # ssh
    ~/.ssh/config: ~/.dotfiles/etc/ssh/config

    # direnv
    ~/.config/direnv/direnv.toml: ~/.dotfiles/etc/direnv/direnv.toml

- shell:
    - command: touch ~/.hushlogin
