- defaults:
    link:
      create: true
      relink: true
      force: true

- clean:
    - "~"

- create:
    - ~/.config
    - ~/.config/direnv
    - ~/.config/ssh
    - ~/Library/Preferences/pypoetry

- link:
    # editorconfig
    ~/.editorconfig: ~/.dotfiles/etc/.editorconfig

    # git
    ~/.gitconfig: ~/.dotfiles/etc/git/.gitconfig
    ~/.gitignore_global: ~/.dotfiles/etc/git/.gitignore_global
    ~/.gitattributes: ~/.dotfiles/etc/git/.gitattributes

    # zsh
    ~/.zshrc: ~/.dotfiles/etc/zsh/.zshrc
    ~/.zsh_plugins.txt: ~/.dotfiles/etc/zsh/.zsh_plugins.txt
    ~/.zsh: 
      path: ~/.dotfiles/etc/zsh/.zsh/*
      glob: true

    # ssh
    ~/.ssh/config: ~/.dotfiles/etc/ssh/config

    # direnv
    ~/.config/direnv/direnv.toml: ~/.dotfiles/etc/direnv/direnv.toml

- shell:
    - command: touch ~/.hushlogin
    